### PR TITLE
Feature US6761-allow_notifier_with_notifiers

### PR DESCRIPTION
**Pull request by rsuddeth**
Add notifier object back in for backwards-compatibility.

@fractalis Can you review, please?

### CODE REVIEW

**Comment by fractalis** [comment]
Looks good; did notice that we still have a reference to `notifiers` in the RSpec for the EmailNotifier (https://github.com/cloudvox/adhearsion-reporter/pull/2/files#diff-1336e2d9aa7a7bdc6eb5452f4246578dR127) - believe that sould be the only line that needs to be changed for the EmailNotifier tests.

**Comment by rsuddeth** [comment]
I made the change to the test locally, and it seems that the multiple notifiers tests are now not passing. I'll have to look into this some more.

**Comment by fractalis** [comment]
You might need to add this before line 181 in the RSpecs (https://github.com/cloudvox/adhearsion-reporter/pull/2/files#diff-1336e2d9aa7a7bdc6eb5452f4246578dL181)

``` ruby
Adhearsion::Events.clear_handlers(:exception)
```

The exception handlers are kept between each of the RSpec `context`s, so we try to notify with the EmailNotifier again but don't have all the set-up to allow the test to pass that was necessary in its specific context.

**Comment by rsuddeth** [comment]
Good question, Ben. I don't see any reason for the index. I've quickly changed the code leave it out, and unit tests aren't broken, but I wonder if I should do more "real" tests.

**Comment by fractalis** [comment]
Thanks Rachel; the original use of the index was an arbitrary decision on my part but I think using the reference to the notifier is a better approach, especially considering I was already using it to call `#init`.

**Comment by rsuddeth** [comment]
Thanks both of you. Changes are made according to comments.
@fractalis Do you want to have another look?

**Comment by rsuddeth** [comment]
@fractalis Is this okay to merge now?

**Comment by fractalis** [comment]
Yep, looks solid to me. @ajayanty Good to merge when you have a chance, thanks!

**Comment by sfgeorge** [comment]
@ajayanty Can you merge when you get a chance?

**Pull request merged**
